version: '3.8'

services:
  icms-backend:
    build:
      context: .
      dockerfile: Dockerfile
        # container_name: icms-backend
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      # Application Configuration
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - API_PREFIX=${API_PREFIX:-api/v1}
      - APP_NAME=${APP_NAME:-ICMS Backend}
      - APP_VERSION=${APP_VERSION:-1.0.0}
      - APP_ABBREVIATION=${APP_ABBREVIATION}
      
      # Database Configuration
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_HOST=${DATABASE_HOST:-postgres}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_NAME=${DATABASE_NAME:-cmsdb}
      - DATABASE_USER=${DATABASE_USER:-cmsadmin}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-cmsadmin}
      
      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1h}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-7d}
      
      # Redis Configuration
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB:-0}
      
      # Storage Configuration
      - STORAGE_PROVIDER=${STORAGE_PROVIDER:-local}
      - STORAGE_LOCAL_PATH=${STORAGE_LOCAL_PATH:-./uploads}
      - STORAGE_LOCAL_BASE_URL=${STORAGE_LOCAL_BASE_URL:-http://localhost:3000/uploads}
      - STORAGE_S3_ENDPOINT=${STORAGE_S3_ENDPOINT}
      - STORAGE_S3_REGION=${STORAGE_S3_REGION}
      - STORAGE_S3_BUCKET=${STORAGE_S3_BUCKET}
      - STORAGE_S3_ACCESS_KEY_ID=${STORAGE_S3_ACCESS_KEY_ID}
      - STORAGE_S3_SECRET_ACCESS_KEY=${STORAGE_S3_SECRET_ACCESS_KEY}
      - STORAGE_S3_FORCE_PATH_STYLE=${STORAGE_S3_FORCE_PATH_STYLE:-true}
      - STORAGE_S3_SIGNED_URL_EXPIRES=${STORAGE_S3_SIGNED_URL_EXPIRES:-3600}
      
      # Backblaze B2 Configuration
      - BACKBLAZE_APPLICATION_KEY_ID=${BACKBLAZE_APPLICATION_KEY_ID}
      - BACKBLAZE_APPLICATION_KEY=${BACKBLAZE_APPLICATION_KEY}
      - BACKBLAZE_BUCKET_ID=${BACKBLAZE_BUCKET_ID}
      - BACKBLAZE_BUCKET_NAME=${BACKBLAZE_BUCKET_NAME}
      - BACKBLAZE_ENDPOINT=${BACKBLAZE_ENDPOINT}
      - BACKBLAZE_MAX_RETRIES=${BACKBLAZE_MAX_RETRIES:-3}
      - BACKBLAZE_RETRY_DELAY=${BACKBLAZE_RETRY_DELAY:-1000}
      
      # Email Configuration
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_SECURE=${EMAIL_SECURE:-false}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      
      # Security Configuration
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS:-12}
      - RATE_LIMIT_TTL=${RATE_LIMIT_TTL:-60}
      - RATE_LIMIT_LIMIT=${RATE_LIMIT_LIMIT:-100}
      - SLOW_DOWN_DELAY=${SLOW_DOWN_DELAY:-1000}
      
      # File Upload Configuration
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - ALLOWED_FILE_TYPES=${ALLOWED_FILE_TYPES}
      - UPLOAD_PATH=${UPLOAD_PATH:-uploads}
      
      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-logs}
      - LOG_MAX_SIZE=${LOG_MAX_SIZE:-20m}
      - LOG_MAX_FILES=${LOG_MAX_FILES:-14d}
      
      # CORS Configuration
      - CORS_ORIGIN=${CORS_ORIGIN}
      - CORS_CREDENTIALS=${CORS_CREDENTIALS:-true}
      
      # Session Configuration
      - SESSION_SECRET=${SESSION_SECRET}
      - SESSION_COOKIE_MAX_AGE=${SESSION_COOKIE_MAX_AGE:-86400000}
      
      # Feature Flags
      - ENABLE_SWAGGER=${ENABLE_SWAGGER:-true}
      - ENABLE_RATE_LIMITING=${ENABLE_RATE_LIMITING:-true}
      - ENABLE_COMPRESSION=${ENABLE_COMPRESSION:-true}
      - ENABLE_HELMET=${ENABLE_HELMET:-true}
      - ENABLE_CORS=${ENABLE_CORS:-true}
      
      # Bootstrap Configuration
      - USEREMAIL=${USEREMAIL:-admin@example.com}
      - USERPASSWORD=${USERPASSWORD:-Admin@123}
      
      # Legacy MinIO Configuration (for backward compatibility)
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_USE_SSL=${MINIO_USE_SSL:-false}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_REGION=${MINIO_REGION}
      - MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT:-9001}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./prisma:/app/prisma

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


